# Generated by Django 2.0.9 on 2021-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se guarda la fecha en la que se creo el modelo o objeto')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se guarda la fecha en que fue llamado el modelo por ultima vez')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.SlugField(max_length=140, unique=True)),
                ('about', models.TextField(max_length=255, verbose_name='circle description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True, help_text='verificar un circulo es la forma de saber si es una comunidad oficial', verbose_name='verificacion de un circulo')),
                ('is_public', models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone know about their existence.', verbose_name='como saber si un circulo es privado o publico')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited circles can grow up to a fixed number of members.', verbose_name='limited')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If circle is limited, this will be the limit on the number of members.')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
